---
title: "gauge_analysis"
author: "John Gardner"
date: "October 9, 2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(dplyr)
library(ggplot2)
library(anytime)
library(lubridate)
library(modeest)
library(sf)
library(mapview)
library(feather)
library(ggthemes)
library(stats)
library(MASS)
library(broom)
library(mapview)
library(tidyr)
library(dataRetrieval)
library(htmlwidgets)
library(ggthemes)
library(leafpop)
library(leaflet)
library(ggpubr)
library(Matching)
library(twosamples)

source("D:/Dropbox/projects/ROTFL/src/ROTFL_functions.R")

knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r make_nests}

load('D:/GoogleDrive/ROTFL/out/rotfl_clean.RData')

# 103 sites with all NA in discharge data. lets remove these
bad_sites <- usgs_full %>% 
  group_by(id) %>%
  mutate(n = sum(!is.na(q))) %>%
  filter(n ==0) %>%
  distinct(id, .keep_all = T)

# make nested data sets for mapping stats
# had to set filters to still remove sites with too little data
# that was messing up stats

### Nest cloud free landsat overpasses
nested_ls <- matched_sats %>%
  group_by(id) %>%
  mutate(n = sum(!is.na(q))) %>%
  # filter to sites that have > 10 Q samples over landsat record
  # cannot effectively compare distributions will small sample size
  dplyr::filter(n > 10) %>%
  dplyr::filter(!id %in% unique(bad_sites$id)) %>%
  nest() %>%
  rename(sat_data=data)

# nest full usgs distribution and join to cloud free
nested_gs <- usgs_full %>%
  group_by(id) %>%
  #mutate(n = sum(!is.na(q))) %>%
  dplyr::filter(id %in% unique(nested_ls$id)) %>%
  nest() %>%
  inner_join(nested_ls,by='id')

#
# nested all (clouds or no clouds) landsat overpasses
nested_ls_all <- landsat_all %>%
  group_by(id) %>%
  mutate(n = sum(!is.na(q))) %>%
  # filter to sites that have > 10 Q samples over landsat record
  # cannot effectively compare distributions will small sample size
  dplyr::filter(n > 10) %>%
  dplyr::filter(!id %in% unique(bad_sites$id)) %>%
  nest() %>%
  rename(sat_data=data)

# nest full usgs distribution and join to all (clouds or no)
nested_gs_all <- usgs_full %>%
  group_by(id) %>%
  #mutate(n = sum(!is.na(q))) %>%
  dplyr::filter(id %in% unique(nested_ls_all$id)) %>%
  nest() %>%
  inner_join(nested_ls_all,by='id')

#
# compare cloudfree landsat Q samples to when landsat NOT sampled
nested_not <- not_matched %>%
  group_by(id) %>%
  #mutate(n = sum(!is.na(q))) %>%
  dplyr::filter(id %in% unique(nested_ls$id)) %>%
  nest() %>%
  inner_join(nested_ls,by='id')

#
# make map of fraction of days cloud free at sites
cloud <- landsat_all %>%
  dplyr::filter(id %in% unique(nested_ls$id)) %>%
  filter(!is.na(q)) %>%
  group_by(id) %>%
  summarise(count_all = n()) %>%
  left_join(landsat_cloud_free %>%
              dplyr::filter(id %in% unique(nested_ls$id)) %>%
              filter(!is.na(q)) %>%
              group_by(id) %>%
              summarise(count_cloudfree = n()),
            by="id"  ) %>%
  mutate(cloud_free_frac = count_cloudfree/count_all)
  
cloud_join <- cloud %>%
  left_join(sites, by="id") %>%
  st_as_sf(coords=c('dec_long_va','dec_lat_va'),crs=4326)

map_cloud<- mapview(cloud_join, zcol='cloud_free_frac', legend=T)

#mapshot(map_cloud,  file="figs/cloud_map.png", url ="figs/cloud_map.html"  )

#write.csv(cloud_join,file='D:/GoogleDrive/ROTFL/out/cloudiness_gauges.csv')

```

## Ks tests

```{r compare_distributions, echo=FALSE}


# Cloud free overpasses ks bootstrapped test
ks_gs <- nested_gs %>% 
# slice(1:3) %>%
  mutate(ks = map2(data,sat_data,myboots)) %>%
  mutate(rbi = map(data, RBIcalc)) %>%
  unnest(ks) %>%
  unnest(rbi) %>%
  dplyr::select(-data, -sat_data) %>%
  mutate(ks_test = ifelse(pvalue_boot < 0.05, "different", "same"))

ks_gs <- ks_gs %>%
  mutate(test = "ks_cloud_free")

# All landsat passes ks bootstrapped test
ks_gs_all <- nested_gs_all %>% 
# slice(1:3) %>%
  mutate(ks = map2(data,sat_data,myboots)) %>%
  mutate(rbi = map(data, RBIcalc)) %>%
  unnest(ks) %>%
  unnest(rbi) %>%
  dplyr::select(-data, -sat_data) %>%
  mutate(ks_test = ifelse(pvalue_boot < 0.05, "different", "same"))

ks_gs_all <- ks_gs_all %>%
  mutate(test = "ks_all_returns")

# comparing landsat overpasses with Q with OUT landsat overpass
ks_gs_not <- nested_not %>% 
# slice(1:3) %>%
  mutate(ks = map2(data,sat_data,myboots)) %>%
  mutate(rbi = map(data, RBIcalc)) %>%
  unnest(ks) %>%
  unnest(rbi) %>%
  dplyr::select(-data, -sat_data) %>%
  mutate(ks_test = ifelse(pvalue_boot < 0.05, "different", "same"))

ks_gs_not <- ks_gs_not %>%
  mutate(test = "ks_cloud_free_unmatched")

# make one long dataframe of different comparisons
ks_bind <- bind_rows(ks_gs, ks_gs_all, ks_gs_not)

#save(ks_gs, ks_gs_all, ks_gs_not, ks_bind, file='D:/GoogleDrive/ROTFL/out/rotfl_kstats.RData')
```



```{r gauge_percentiles, echo=F}

# make look up table of population flow percentiles by site to later join to find what population percentiles corresponed with min/max sample Q

percentiles_pop <- full_sats %>%
  dplyr::select(id, q_pop) %>%
  arrange(id, q_pop) %>%
  group_by(id) %>%
  mutate(prob_pop = 1-cume_dist(q_pop)) %>%
  distinct(id, q_pop, prob_pop, .keep_all = T)
  
# extract mode, max, min per gage. find mode, min, max for population and sample per site. 
flow_stats <- full_sats %>%
  dplyr::select(id, q_sample, q_pop) %>%
  # remove sites that have no landsat samples, or no gage flow data
  dplyr::filter(id %in% unique(nested_ls$id)) %>%
  # calculate modal, max, min Q for sample and population
  group_by(id) %>%
  summarise_at(vars(q_sample, q_pop), list(~ min(., na.rm=T), ~ max(., na.rm=T), ~ median(., na.rm = TRUE), ~mlv(., na.rm=T ))) %>%
  rename(q_sample_mode = q_sample_mlv, q_pop_mode = q_pop_mlv) %>%
  mutate(mode_ratio = q_sample_mode / q_pop_mode) %>%
  ungroup() %>%
  # join in what "poplution" flow percentile corresponds to sample max/min 
  inner_join(., percentiles_pop, by=c("id", "q_sample_max"="q_pop")) %>%
  rename(prob_sample_max = prob_pop ) %>% 
  inner_join(., percentiles_pop, by=c("id", "q_sample_min"="q_pop")) %>%
  rename(prob_sample_min = prob_pop) %>% 
  mutate(percentile_range_sample = (prob_sample_min - prob_sample_max) *100)
  
# join to usgs site info
flow_stats_site <- flow_stats %>%
  left_join(sites, by = "id") 


# bind ks tests to flow stats and site info and write to csv
ks_bind_join <- ks_bind %>%
  inner_join(flow_stats_site, by="id") %>%
  ungroup()

#write_csv(ks_bind_join, "D:/GoogleDrive/ROTFL/out/ks_tests_sites_all.csv")


```

```{r stats}


lm_same <- lm(d_boot~cloud_free_frac, data=cloud_ks %>%
                filter(ks_test=="same"))

lm_diff <- lm(d_boot~cloud_free_frac, data=cloud_ks %>%
                filter(ks_test=="different"))


spear_cloud <- cloud_ks %>%
  st_set_geometry(NULL) %>%
  as_tibble() %>%
  group_by(ks_test) %>%
  nest() %>%
  mutate(cor = purrr::map(data, ~cor.test(.x$cloud_free_frac, .x$d_boot, method="spearm"))) %>%
  mutate(t = purrr::map(cor, tidy)) %>%
  unnest(t)

spear_rbi <- cloud_ks %>%
  st_set_geometry(NULL) %>%
  as_tibble() %>%
  group_by(ks_test) %>%
  nest() %>%
  mutate(cor = purrr::map(data, ~cor.test(.x$rbi, .x$d_boot, method="spearm"))) %>%
  mutate(t = purrr::map(cor, tidy)) %>%
  unnest(t)

```


```{r figure_4, echo=F}

# make figure 4
cloud_ks <- cloud_join %>%
  inner_join(ks_bind_join %>%
               filter(test =="ks_cloud_free") %>%
               dplyr::select(id:percentile_range_sample),
             by="id")

# relating D stat from KS test to fraction cloud free days per gauge
plot1 <- ggplot(cloud_ks, aes(x=cloud_free_frac, y=d_boot, color=ks_test))+
  geom_point(fill=NA, shape=21, size=0.75)+
  # geom_smooth(method="lm") +
  theme_few() +
  xlab("Fraction cloud-free") +
  ylab("D statistic (KS-test)") +
  theme(legend.position = c(0.79, 0.95),
        legend.background = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.05, 'lines'),
        axis.title = element_text(size=9),
        axis.text = element_text(size=9)) +
  scale_color_manual(values=c("grey", "black"), labels=c("p < 0.05", "p > 0.05"), name="")

# same with best fit lines
plot1_lines <- ggplot(cloud_ks, aes(x=cloud_free_frac, y=d_boot, color=ks_test))+
 geom_point(fill=NA, shape=21, size=0.75)+
  geom_smooth(method="lm", se=F) +
  theme_few() +
  xlab("Fraction cloud-free") +
  ylab("D statistic (KS-test)") +
  theme(legend.position = c(0.79, 0.95),
        legend.background = element_blank(),
        legend.key.size = unit(0.05, 'lines'),
        legend.text = element_text(size=8),
        axis.title = element_text(size=9),
        axis.text = element_text(size=9)) +
  scale_color_manual(values=c("grey", "black"), labels=c("p < 0.05", "p > 0.05"), name="")


# relating D stat from KS test to flow flashiness (Richards-Baker Index) per gauge 
plot2 <- ggplot(cloud_ks) +
  geom_point(aes(x=rbi, y=d_boot, color=ks_test), fill=NA, shape=21, size=0.75)+
  theme_few() +
  scale_x_log10(breaks = c(0.03, 0.1, 0.3, 1.0),
                labels = c("0.03", "0.1", "0.3", "1.0")) +
  xlab("Flashiness Index") +
  ylab("") +
  theme(legend.position = "none",
        legend.background = element_blank(),
        axis.title = element_text(size=9),
        axis.text = element_text(size=9)) +
  scale_color_manual(values=c("grey", "black"), labels=c("p < 0.05", "p > 0.05"), name="") 

# cumulative distribution function of the range of flow percentiles in 
# the whole gague record that is captured by Landsat sampling...
# >90% of gages capture 97% perecntiles of flow

plot3 <- ggplot(ks_bind_join %>%
         filter(test == "ks_cloud_free"),
       aes(percentile_range_sample/100)) +
  stat_ecdf(geom = "point", alpha=0.5) +
  theme_few() +
  ylab("CDF of gauges") +
  xlab("Proportion of flow quantiles ") +
  geom_hline(aes(yintercept= 0.1), col="red", linetype=2) +
  geom_vline(aes(xintercept=0.97), col="red", linetype=2) +
  theme(legend.position = "none",
        axis.title = element_text(size=9),
        axis.text = element_text(size=9)) 

#ggsave(paste('figs/', "proportion_flows_captured2.png", sep=""), units='in', width = 3.2, height=3, dpi = 300)

library(egg)

ggpubr::ggarrange(plot1, plot2, plot3, nrow=1, ncol=3)
#ggsave(paste('D:/Dropbox/projects/ROTFL/figs/', "Fig4_gauges_row2.tiff", sep=""), units='in', width = 6, height=2., dpi = 300)
#ggsave(paste('D:/Dropbox/projects/ROTFL/figs/', "Fig4_gauges_row2.png", sep=""), units='in', width = 6, height=2, dpi = 300)

# save 3 panel fig with best fit lines
ggpubr::ggarrange(plot1_lines, plot2, plot3, nrow=1, ncol=3)
#ggsave(paste('D:/Dropbox/projects/ROTFL/figs/', "Fig4_gauges_lines_row2.tiff", sep=""), units='in', width = 6, height=2, dpi = 300)
#ggsave(paste('D:/Dropbox/projects/ROTFL/figs/', "Fig4_gauges_lines_row2.png", sep=""), units='in', width = 6, height=2, dpi = 300)

```

